version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../models:/app/models
      - ../.env.example:/app/.env.example
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - LOCAL_MODEL_PATH=${LOCAL_MODEL_PATH}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - VECTOR_BACKEND=${VECTOR_BACKEND}
      - USE_GPU=${USE_GPU}

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - backend
